import "./BookSamples.css";

export default function BookSamples() {
    return (
        <div className="samples">
            <h2>Sample Books Generated by BookAI</h2>
            <p>Explore some of the captivating books created using our AI technology.</p>
            <div className="sample-container">
                <div className="book-sample">
                    <div className="cover-page">
                        <img src="/paradox.png"></img>
                    </div>
                    <h3>Science Fiction</h3>
                    <p>"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."</p>
                    <a href="/">Read More</a>
                </div>
                <div className="book-sample">
                    <div className="cover-page">
                        <img src="/cover2.jpg"></img>
                    </div>
                    <h3>Mystery</h3>
                    <p style={{marginTop: "1.25rem"}}>"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."</p>
                    <a href="/" style={{marginTop: "0.25rem"}}>Read More</a>
                </div>
                <div className="book-sample">
                    <div className="cover-page">
                        <img src="/cover3.jpg"></img>
                    </div>
                    <h3>Fantasy</h3>
                    <p>"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."</p>
                    <a href="/">Read More</a>
                </div>
            </div>
        </div>
    )
}